name: sorting
description: A new Flutter project.
version: 1.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  animations: ^1.0.0+5
  provider: ^4.0.4
  numberpicker: ^1.2.0
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon.png"

  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          style: normal
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 100
